Repository Travel-WithMe/TravelWithMe-sever, pull requests merged in 2023-05, with the labels that each got.

#52 [feat -> develop] feat - #44 : 동행 매칭 취소 테스트 코드 오류 수정
  travel-with-me/src/test/java/com/frog/travelwithme/intergration/buddy/BuddyIntegrationTest.java
Labels: 🐞 fix

#63 [patch -> develop] chore - #56: Update gradle.yml
  .github/workflows/gradle.yml
Labels: ⚙️ chore, 🔗 CI/CD

#64 [develop -> main] feat - #56: CodeDeploy 설정 추가
  .github/workflows/gradle.yml
Labels: ⚙️ chore, 🔗 CI/CD

#68 [feat -> develop] feat - #65: Git actions 빌드 에러수정
  travel-with-me/src/test/java/com/frog/travelwithme/TravelWithMeApplicationTests.java
  travel-with-me/src/test/java/com/frog/travelwithme/unit/redis/service/RedisCrudTest.java
  travel-with-me/src/test/java/com/frog/travelwithme/unit/security/auth/controller/AuthControllerTest.java
Labels: ✅ test, 🔗 CI/CD

#71 [develop -> main] feat - #65: CI/CD build시 test 코드 오류 수정
  travel-with-me/src/test/java/com/frog/travelwithme/unit/common/config/AES128ConfigTest.java
  travel-with-me/src/test/java/com/frog/travelwithme/unit/redis/service/RedisCrudTest.java
  travel-with-me/src/test/java/com/frog/travelwithme/unit/security/auth/controller/AuthControllerTest.java
Labels: ✅ test, 🔗 CI/CD

#79 [develop -> main] fix - #65: merge 오류수정
  .github/workflows/gradle.yml
Labels: 🐞 fix, 🔗 CI/CD

#80 [develop -> main] fix - #65: merge 오류수정
  .github/workflows/gradle.yml
Labels: 🐞 fix, 🔗 CI/CD

#82 [develop -> main] feat - #65: rebase 오류수정
  .github/workflows/gradle.yml
Labels: 🐞 fix, 🔗 CI/CD

#88 [feat -> develop] feat - #55: 동행 매칭거절 API 작성
  travel-with-me/src/main/java/com/frog/travelwithme/domain/buddy/controller/MatchingController.java
  travel-with-me/src/main/java/com/frog/travelwithme/domain/buddy/repository/RecruitmentCustomRepository.java
  travel-with-me/src/main/java/com/frog/travelwithme/domain/buddy/repository/RecruitmentCustomRepositoryImpl.java
  travel-with-me/src/main/java/com/frog/travelwithme/domain/buddy/service/MatchingService.java
  travel-with-me/src/main/java/com/frog/travelwithme/domain/buddy/service/RecruitmentService.java
  travel-with-me/src/main/java/com/frog/travelwithme/global/enums/EnumCollection.java
  travel-with-me/src/main/java/com/frog/travelwithme/global/exception/ExceptionCode.java
  travel-with-me/src/test/java/com/frog/travelwithme/intergration/buddy/MatchingIntegrationTest.java
  travel-with-me/src/test/java/com/frog/travelwithme/unit/domain/buddy/controller/MatchingControllerTest.java
  travel-with-me/src/test/java/com/frog/travelwithme/unit/domain/buddy/repository/RecruitmentRepositoryTest.java
  travel-with-me/src/test/java/com/frog/travelwithme/unit/domain/buddy/service/MatchingServiceTest.java
  travel-with-me/src/test/java/com/frog/travelwithme/unit/domain/buddy/service/RecruitmentServiceTest.java
Labels: ✨ feat, ✅ test

#97 [feat -> develop] feat - #50: 동행 모집글 신청 회원 조회 기능 개발
  travel-with-me/src/main/java/com/frog/travelwithme/domain/buddy/controller/RecruitmentController.java
  travel-with-me/src/main/java/com/frog/travelwithme/domain/buddy/controller/dto/RecruitmentDto.java
  travel-with-me/src/main/java/com/frog/travelwithme/domain/buddy/mapper/RecruitmentMapper.java
  travel-with-me/src/main/java/com/frog/travelwithme/domain/buddy/repository/MatchingCustomRepository.java
  travel-with-me/src/main/java/com/frog/travelwithme/domain/buddy/repository/MatchingCustomRepositoryImpl.java
  travel-with-me/src/main/java/com/frog/travelwithme/domain/buddy/repository/RecruitmentCustomRepository.java
  travel-with-me/src/main/java/com/frog/travelwithme/domain/buddy/repository/RecruitmentCustomRepositoryImpl.java
  travel-with-me/src/main/java/com/frog/travelwithme/domain/buddy/service/MatchingService.java
  travel-with-me/src/main/java/com/frog/travelwithme/domain/buddy/service/RecruitmentService.java
  travel-with-me/src/main/java/com/frog/travelwithme/global/exception/ExceptionCode.java
  travel-with-me/src/test/java/com/frog/travelwithme/intergration/buddy/MatchingIntegrationTest.java
  travel-with-me/src/test/java/com/frog/travelwithme/intergration/buddy/RecruitmentIntegrationTest.java
  travel-with-me/src/test/java/com/frog/travelwithme/unit/domain/buddy/controller/RecruitmentControllerTest.java
  travel-with-me/src/test/java/com/frog/travelwithme/unit/domain/buddy/repository/MatchingRepositoryTest.java
  travel-with-me/src/test/java/com/frog/travelwithme/unit/domain/buddy/repository/RecruitmentRepositoryTest.java
  travel-with-me/src/test/java/com/frog/travelwithme/unit/domain/buddy/service/RecruitmentServiceTest.java
  travel-with-me/src/test/java/com/frog/travelwithme/utils/StubData.java
  travel-with-me/src/test/java/com/frog/travelwithme/utils/snippet/response/ResponseSnippet.java
Labels: ✨ feat, ✅ test

#102 [feat -> develop] fix - #96: 테스트 오류 해결
  travel-with-me/src/main/java/com/frog/travelwithme/global/config/AwsS3Config.java
Labels: ✅ test
