Repository Travel-WithMe/TravelWithMe-sever, pull requests merged in 2023-06, with the labels that each got.

#117 [fix -> develop] fix - #116: 기능 배포완료후 버그수정
  travel-with-me/src/main/java/com/frog/travelwithme/global/config/SecurityConfiguration.java
  travel-with-me/src/main/resources/db/data.sql
Labels: 🐞 fix

#118 [develop -> main] fix - #116: 기능 배포완료후 버그수정
  travel-with-me/src/main/java/com/frog/travelwithme/global/config/SecurityConfiguration.java
  travel-with-me/src/main/resources/db/data.sql
Labels: 🐞 fix

#120 [develop -> main] fix - #116: 기능 배포완료후 버그수정
  travel-with-me/src/main/java/com/frog/travelwithme/domain/recruitment/controller/BuddyController.java
  travel-with-me/src/main/java/com/frog/travelwithme/domain/recruitment/repository/BuddyCustomRepository.java
  travel-with-me/src/main/java/com/frog/travelwithme/domain/recruitment/repository/BuddyCustomRepositoryImpl.java
  travel-with-me/src/main/java/com/frog/travelwithme/domain/recruitment/repository/BuddyRepository.java
  travel-with-me/src/main/java/com/frog/travelwithme/domain/recruitment/service/BuddyService.java
  travel-with-me/src/main/java/com/frog/travelwithme/global/config/SecurityConfiguration.java
Labels: 🐞 fix

#129 [develop -> main] fix - #127: 배포중 발생 문제 수정
  travel-with-me/src/main/resources/db/data.sql
Labels: 🐞 fix

#141 [develop -> main] feat: 기능 배포
  travel-with-me/src/main/java/com/frog/travelwithme/domain/feed/controller/FeedController.java
  travel-with-me/src/main/java/com/frog/travelwithme/domain/feed/repository/FeedCustomRepository.java
  travel-with-me/src/main/java/com/frog/travelwithme/domain/feed/repository/FeedCustomRepositoryImpl.java
  travel-with-me/src/main/java/com/frog/travelwithme/domain/feed/service/FeedService.java
  travel-with-me/src/main/resources/db/data-mysql.sql
  travel-with-me/src/test/java/com/frog/travelwithme/intergration/feed/FeedIntegrationTest.java
  travel-with-me/src/test/java/com/frog/travelwithme/unit/domain/feed/controller/FeedControllerTest.java
Labels: ✨ feat, 🐞 fix, 📄 docs, 🧨 show, ✅ test, 🔗 CI/CD

#143 fix - #142: SQLIntegrityConstraintViolationException 해결
  travel-with-me/src/main/resources/db/data-mysql.sql
Labels: 🐞 fix

#146 [feat -> develop] feat - #145: Discord에서 log 확인할 수 있도록 자동화
  travel-with-me/build.gradle
  travel-with-me/src/main/resources/logback-spring.xml
Labels: ⚙️ chore, ✨ feat
