Repository Travel-WithMe/TravelWithMe-sever, pull requests merged in 2023-04, with the labels that each got.

#12 [feat -> develop] feat - #11: Enum 데이터 취합 클래스 작성
  travel-with-me/src/main/java/com/frog/travelwithme/common/EnumCollection.java
  travel-with-me/src/main/java/com/frog/travelwithme/common/EnumType.java
Labels: ✨ feat, 🧨 show

#20 [feat -> develop] rename - #19: 패키지 구조 변경
  travel-with-me/src/main/java/com/frog/travelwithme/domain/member/entity/Member.java
  travel-with-me/src/main/java/com/frog/travelwithme/domain/member/service/MemberService.java
  travel-with-me/src/main/java/com/frog/travelwithme/global/config/AES128Config.java
  travel-with-me/src/main/java/com/frog/travelwithme/global/config/EmbeddedRedisConfig.java
  travel-with-me/src/main/java/com/frog/travelwithme/global/config/PasswordEncoderConfig.java
  travel-with-me/src/main/java/com/frog/travelwithme/global/config/RedisConfig.java
  travel-with-me/src/main/java/com/frog/travelwithme/global/enums/EnumCollection.java
  travel-with-me/src/main/java/com/frog/travelwithme/global/enums/EnumType.java
  travel-with-me/src/main/java/com/frog/travelwithme/global/security/auth/filter/JwtAuthenticationFilter.java
  travel-with-me/src/main/java/com/frog/travelwithme/global/security/auth/service/AuthService.java
  travel-with-me/src/main/java/com/frog/travelwithme/global/security/auth/utils/CustomAuthorityUtils.java
  travel-with-me/src/main/java/com/frog/travelwithme/global/security/config/SecurityConfiguration.java
  travel-with-me/src/main/java/com/frog/travelwithme/global/utils/CustomBeanUtils.java
  travel-with-me/src/test/java/com/frog/travelwithme/unit/common/config/AES128ConfigTest.java
Labels: 📂 rename

#23 [feat -> develop] feat - #21: submodule gradle, gitignore
  travel-with-me/.gitignore
  travel-with-me/build.gradle
Labels: ⚙️ chore

#34 [feat -> develop] test - 31: Member 단위 테스트(Service, Respository)
  travel-with-me/src/test/java/com/frog/travelwithme/unit/domain/member/repository/MemberRepositoryTest.java
  travel-with-me/src/test/java/com/frog/travelwithme/unit/domain/member/service/MemberServiceTest.java
  travel-with-me/src/test/java/com/frog/travelwithme/utils/StubData.java
Labels: ✅ test

#41 [feat -> develop] feat - #40: Member, Auth API 문서 생성
  travel-with-me/.gitignore
  travel-with-me/src/docs/asciidoc/index.adoc
  travel-with-me/src/test/java/com/frog/travelwithme/intergration/member/MemberIntegrationTest.java
Labels: 🔨 refactor, 📄 docs
